name: .NET
on:
  push:
    tags:        
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish (Linux)
      run: dotnet publish --output out-linux-x64 --runtime linux-x64 --no-self-contained
    - name: Publish (Windows)
      run: dotnet publish --output out-win-x64 --runtime win-x64 --no-self-contained
    - name: Package (Linux)
      run: tar -czf assetto-server-linux-x64.tar.gz out-linux-x64/*
    - name: Package (Windows)
      run: zip assetto-server-win-x64.zip out-win-x64/*
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: yes
        files: |
          assetto-server-linux-x64.tar.gz
          assetto-server-win-x64.zip
